mongodb:
  user: diversify
  password: Et3wyuQEsp2ru1S0
  db: diversify
  assets: assets
  allocation: allocation
  host: db
  port: 27017
config:
  asset_classes:
    - Fonds Euros
    - Actions
    - Immobilier